import type { PtyInjector } from '../shared/actions/pty-inject';

// ---------------------------------------------------------------------------
// Unified token usage — all fields default 0 for missing data
// ---------------------------------------------------------------------------
export interface UnifiedTokenUsage {
  /** Fresh input tokens (raw + cache_creation, NOT including cache_read). */
  freshInputTokens: number;
  /** Tokens served from prompt cache (free / discounted). */
  cacheReadTokens: number;
  /** Output tokens generated by the model. */
  outputTokens: number;
  /** Reasoning tokens inside the output (o3/o4 only; 0 otherwise). */
  reasoningTokens: number;
}

// ---------------------------------------------------------------------------
// Unified tool call
// ---------------------------------------------------------------------------
export type UnifiedToolKind = 'builtin' | 'skill' | 'mcp' | 'task' | 'shell' | 'patch' | 'search';

export interface UnifiedToolCall {
  id: string;
  kind: UnifiedToolKind;
  name: string;
  input: unknown;
  output: unknown | null;
  isError?: boolean;
}

// ---------------------------------------------------------------------------
// Unified API call entry (one LLM round-trip within a turn)
// ---------------------------------------------------------------------------
export interface ApiCallEntry {
  /** 1-based index within the turn. */
  callIndex: number;
  /** Tool calls triggered in this round. */
  toolCalls: UnifiedToolCall[];
  /** Assistant text returned (may be empty if only tool calls). */
  assistantText: string;
  /** Token usage for this specific API call. */
  tokenUsage: UnifiedTokenUsage;
}

// ---------------------------------------------------------------------------
// Unified prompt turn
// ---------------------------------------------------------------------------
export interface UnifiedPromptTurn {
  /** 1-based index in the session. */
  index: number;
  /** The user's input text (collapsed to a single string). */
  userText: string;
  /** Timestamp of the user prompt (ms epoch). */
  ts: number;
  /** One entry per LLM API call in this turn (tool loop = multiple entries). */
  apiCalls: ApiCallEntry[];
  /** Total token consumption across all API calls in this turn. */
  totalTokens: UnifiedTokenUsage;
  /** True if the user interrupted the turn before completion. */
  aborted: boolean;
  /** Adapter-internal: uuid/id used for raw-viewer cross-reference. */
  _internalId?: string;
}

// ---------------------------------------------------------------------------
// Session metadata
// ---------------------------------------------------------------------------
export interface UnifiedSessionMeta {
  kind: 'claude' | 'codex';
  model: string | null;
  cwd: string;
  /** Claude: permissionMode; Codex: approval_mode. */
  mode: string | null;
  /** Unique thread/session identifier. */
  threadId: string;
}

// ---------------------------------------------------------------------------
// Environment config (read-only view)
// ---------------------------------------------------------------------------
export interface EnvConfig {
  baseUrl: string | null;
  model: string | null;
  apiKeyMasked: string | null;
}

// ---------------------------------------------------------------------------
// SSE strategy (injected into ProxyServer)
// ---------------------------------------------------------------------------
export interface SseStrategy {
  /** Path that identifies capture-worthy requests (e.g. '/v1/messages'). */
  captureEndpointPath: string;
  /** Extract a stable message ID from the raw SSE buffer. */
  parseMessageId(buf: string): string | null;
  /** Extract token usage from the raw SSE buffer. */
  parseUsage(buf: string): UnifiedTokenUsage | null;
  /** Merge SSE deltas into a human-readable string. */
  mergeSse(buf: string): string;
}

// ---------------------------------------------------------------------------
// IAdapter interface
// ---------------------------------------------------------------------------
export interface IAdapter {
  readonly kind: 'claude' | 'codex';

  /** Begin watching `sessionFile` (or the equivalent path). */
  startWatching(sessionFile: string): Promise<void>;
  /** Stop watching and free resources. */
  stopWatching(): void;
  /** Register a callback for data updates. */
  onUpdate(cb: () => void): { dispose: () => void };

  /** Linearized prompt turns (ascending order). */
  getPromptTurns(): UnifiedPromptTurn[];
  /** System prompt if available (Codex: from session_meta; Claude: only via proxy). */
  getSystemPrompt(): string | null;
  /** Current session metadata. */
  getMetadata(): UnifiedSessionMeta;

  /** Inject a launch command into the terminal. proxyUrl is set only when the
   *  proxy is currently enabled (caller passes live state, not a cached file). */
  launch(injector: PtyInjector, sessionId: string, proxyUrl?: string | null): Promise<void>;
  /** Current mode string. */
  getMode(): string | null;
  /** Change mode (Claude: Shift+Tab / slash; Codex: display-only). */
  setMode(mode: string, injector: PtyInjector, sessionId: string): Promise<void>;
  /** Read-only env configuration for display. */
  getEnvConfig(): EnvConfig;

  /** Set up env to route traffic through local proxy. */
  writeProxyEnv(proxyUrl: string): Promise<void>;
  /** Restore env to original base URL. */
  restoreEnv(): Promise<void>;
  /** Return the SSE strategy for the proxy server. */
  getSseStrategy(): SseStrategy;
}
