import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const DATA_DIR = path.join(os.homedir(), '.termcat', 'plugins', 'ai_code_power');
const PRESETS_PATH = path.join(DATA_DIR, 'presets.json');
export const ACTIVE_ENV_PATH = path.join(DATA_DIR, 'active.env');

export interface Preset {
  id: string;
  name: string;
  apiKey?: string;
  authToken?: string;
  baseUrl?: string;
  model?: string;
  maxTokens?: number;
  extraEnv?: Record<string, string>;
}

interface PresetsFile {
  version: number;
  activePresetId: string | null;
  presets: Preset[];
}

function shellEscape(value: string): string {
  return "'" + value.replaceAll("'", "'\\''") + "'";
}

export function generateActiveEnv(preset: Preset, opts?: { overrideBaseUrl?: string }): string {
  const keysToSet: string[] = [];
  const exportLines: string[] = [];

  const push = (key: string, line: string) => { keysToSet.push(key); exportLines.push(line); };

  if (preset.apiKey) push('ANTHROPIC_API_KEY', `export ANTHROPIC_API_KEY=${shellEscape(preset.apiKey)}`);
  if (preset.authToken) push('ANTHROPIC_AUTH_TOKEN', `export ANTHROPIC_AUTH_TOKEN=${shellEscape(preset.authToken)}`);
  const effectiveBaseUrl = opts?.overrideBaseUrl ?? preset.baseUrl;
  if (effectiveBaseUrl) push('ANTHROPIC_BASE_URL', `export ANTHROPIC_BASE_URL=${shellEscape(effectiveBaseUrl)}`);
  if (preset.model) push('ANTHROPIC_MODEL', `export ANTHROPIC_MODEL=${shellEscape(preset.model)}`);
  if (typeof preset.maxTokens === 'number') push('ANTHROPIC_MAX_TOKENS', `export ANTHROPIC_MAX_TOKENS=${preset.maxTokens}`);
  for (const [k, v] of Object.entries(preset.extraEnv ?? {})) {
    if (!/^[A-Z_][A-Z0-9_]*$/.test(k)) continue;
    push(k, `export ${k}=${shellEscape(v)}`);
  }

  const marker = keysToSet.length
    ? `export __TC_ACP_MANAGED_KEYS=${shellEscape(keysToSet.join(' '))}`
    : 'unset __TC_ACP_MANAGED_KEYS';

  return [
    `# Generated by TermCat ai-code-power plugin - do not edit`,
    `# Active preset: ${preset.name} (${preset.id})`,
    '',
    '# Cleanup managed keys from previous source',
    'if [ -n "${__TC_ACP_MANAGED_KEYS:-}" ]; then',
    '  eval "set -- $__TC_ACP_MANAGED_KEYS"',
    '  for __tc_acp_k in "$@"; do unset "$__tc_acp_k"; done',
    '  unset __tc_acp_k',
    'fi',
    '',
    ...exportLines,
    marker,
    '',
  ].join('\n');
}

export class PresetStore {
  private presets: Preset[] = [];
  private activePresetId: string | null = null;

  async load(): Promise<void> {
    try {
      const raw = await fs.promises.readFile(PRESETS_PATH, 'utf-8');
      const data = JSON.parse(raw) as PresetsFile;
      this.presets = Array.isArray(data.presets) ? data.presets : [];
      this.activePresetId = data.activePresetId ?? null;
    } catch { /* no presets yet */ }
  }

  list(): Preset[] { return this.presets; }
  getActive(): Preset | null { return this.presets.find((p) => p.id === this.activePresetId) ?? null; }

  async upsert(preset: Preset): Promise<void> {
    const idx = this.presets.findIndex((p) => p.id === preset.id);
    if (idx >= 0) this.presets[idx] = preset;
    else this.presets.push(preset);
    await this.save();
  }

  async setActive(id: string): Promise<void> {
    this.activePresetId = id;
    await this.save();
  }

  async writeActiveEnv(preset: Preset, opts?: { overrideBaseUrl?: string }): Promise<void> {
    await fs.promises.mkdir(DATA_DIR, { recursive: true });
    const content = generateActiveEnv(preset, opts);
    const tmp = ACTIVE_ENV_PATH + '.tmp';
    await fs.promises.writeFile(tmp, content, 'utf-8');
    await fs.promises.rename(tmp, ACTIVE_ENV_PATH);
  }

  activeEnvPath(): string { return ACTIVE_ENV_PATH; }

  private async save(): Promise<void> {
    await fs.promises.mkdir(DATA_DIR, { recursive: true });
    const data: PresetsFile = { version: 1, activePresetId: this.activePresetId, presets: this.presets };
    const tmp = PRESETS_PATH + '.tmp';
    await fs.promises.writeFile(tmp, JSON.stringify(data, null, 2), 'utf-8');
    await fs.promises.rename(tmp, PRESETS_PATH);
  }
}
