import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

// Shares the plugin data dir with the Claude preset store, but a separate file
// so the two CLIs' presets never collide.
const DATA_DIR = path.join(os.homedir(), '.termcat', 'plugins', 'ai_code_power');
const PRESETS_PATH = path.join(DATA_DIR, 'codex-presets.json');
export const CODEX_ACTIVE_ENV_PATH = path.join(DATA_DIR, 'codex-active.env');

export interface CodexPreset {
  id: string;
  name: string;
  apiKey?: string;   // OPENAI_API_KEY — the only field codex reads from the env
  baseUrl?: string;  // injected at launch via `-c openai_base_url=...`
  model?: string;    // injected at launch via `-c model=...`
}

interface CodexPresetsFile {
  version: number;
  activePresetId: string | null;
  presets: CodexPreset[];
}

function shellEscape(value: string): string {
  return "'" + value.replaceAll("'", "'\\''") + "'";
}

/**
 * Codex only honours OPENAI_API_KEY from the environment (baseUrl/model have no
 * env var and ride on `-c` flags at launch instead). So the env file just exports
 * the key, guarded by the same cleanup prologue Claude uses — re-sourcing it never
 * leaves a stale key behind.
 */
export function generateCodexActiveEnv(preset: CodexPreset): string {
  const exportLines: string[] = [];
  const keysToSet: string[] = [];
  if (preset.apiKey) {
    keysToSet.push('OPENAI_API_KEY');
    exportLines.push(`export OPENAI_API_KEY=${shellEscape(preset.apiKey)}`);
  }

  const marker = keysToSet.length
    ? `export __TC_ACP_CODEX_MANAGED_KEYS=${shellEscape(keysToSet.join(' '))}`
    : 'unset __TC_ACP_CODEX_MANAGED_KEYS';

  return [
    `# Generated by TermCat ai-code-power plugin (codex) - do not edit`,
    `# Active preset: ${preset.name} (${preset.id})`,
    '',
    '# Cleanup managed keys from previous source',
    'if [ -n "${__TC_ACP_CODEX_MANAGED_KEYS:-}" ]; then',
    '  eval "set -- $__TC_ACP_CODEX_MANAGED_KEYS"',
    '  for __tc_acp_k in "$@"; do unset "$__tc_acp_k"; done',
    '  unset __tc_acp_k',
    'fi',
    '',
    ...exportLines,
    marker,
    '',
  ].join('\n');
}

export class CodexPresetStore {
  private presets: CodexPreset[] = [];
  private activePresetId: string | null = null;

  async load(): Promise<void> {
    try {
      const raw = await fs.promises.readFile(PRESETS_PATH, 'utf-8');
      const data = JSON.parse(raw) as CodexPresetsFile;
      this.presets = Array.isArray(data.presets) ? data.presets : [];
      this.activePresetId = data.activePresetId ?? null;
    } catch { /* no presets yet */ }
  }

  list(): CodexPreset[] { return this.presets; }
  getActive(): CodexPreset | null { return this.presets.find((p) => p.id === this.activePresetId) ?? null; }

  async upsert(preset: CodexPreset): Promise<void> {
    const idx = this.presets.findIndex((p) => p.id === preset.id);
    if (idx >= 0) this.presets[idx] = preset;
    else this.presets.push(preset);
    await this.save();
  }

  async setActive(id: string): Promise<void> {
    this.activePresetId = id;
    await this.save();
  }

  async writeActiveEnv(preset: CodexPreset): Promise<void> {
    await fs.promises.mkdir(DATA_DIR, { recursive: true });
    const content = generateCodexActiveEnv(preset);
    const tmp = CODEX_ACTIVE_ENV_PATH + '.tmp';
    await fs.promises.writeFile(tmp, content, 'utf-8');
    await fs.promises.rename(tmp, CODEX_ACTIVE_ENV_PATH);
  }

  activeEnvPath(): string { return CODEX_ACTIVE_ENV_PATH; }

  private async save(): Promise<void> {
    await fs.promises.mkdir(DATA_DIR, { recursive: true });
    const data: CodexPresetsFile = { version: 1, activePresetId: this.activePresetId, presets: this.presets };
    const tmp = PRESETS_PATH + '.tmp';
    await fs.promises.writeFile(tmp, JSON.stringify(data, null, 2), 'utf-8');
    await fs.promises.rename(tmp, PRESETS_PATH);
  }
}
